# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        exclude: "_ai_.+\\.(py|scad)"
        exclude_types: [svg]
      - id: end-of-file-fixer
        exclude: "_ai_.+\\.(py|scad)"
        exclude_types: [svg]
      - id: check-yaml
        exclude: "^partcad/tests/unit/data/project_config_(template|include).yaml$"
      - id: check-added-large-files
      # https://github.com/docker/for-mac/issues/5029
      # - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-symlinks
      - id: detect-private-key
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.29.4
    hooks:
      - id: check-dependabot
      - id: check-github-actions
      - id: check-github-workflows
  - repo: https://github.com/python-poetry/poetry
    rev: 1.8.4 # add version here
    hooks:
      - id: poetry-check
      - id: poetry-lock
      - id: poetry-export
        args: [
          "--format=requirements.txt",
          "--output=requirements.txt",
          "--with=dev",
          "--with=partcad",
          "--with=cli",
          "--with=docs"
        ]
      - id: poetry-install
  - repo: local
    hooks:
    - id: shellcheck
      name: ShellCheck
      entry: shellcheck
      language: system
      types: [shell]
      args: ["-e", "SC1091"]  # Optional: exclude specific checks
      # args: ["--severity=warning"]  # Optional: show only errors and warnings
