[project]
name = "partcad-utils"
version = "0.7.153"
description = "Shared lightweight utilities for PartCAD (logging, telemetry, user config)"
readme = "README.md"
keywords = ["cad", "partcad", "logging", "telemetry", "config"]
requires-python = ">=3.10,<3.15"
license = {file = "LICENSE.txt"}
authors = [
  {name = "PartCAD", email = "support@partcad.org" }
]
maintainers = [
  {name = "PartCAD", email = "support@partcad.org" }
]
dynamic = ["dependencies"]

classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
]

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}

[project.urls]
Homepage = "https://github.com/partcad/partcad"
Issues = "https://github.com/partcad/partcad/issues"
