//@ts-check
//
// PartCAD, 2026
//
// Licensed under Apache License, Version 2.0.
//
// Writes `partcad.txt`, the dictionary Code Spell Checker is given for the two
// languages this extension owns -- `partcad-assy` and `partcad-yaml` -- so that
// what PartCAD's schemas spell is not underlined as a typo in every file. See
// `cspell-ext.json` for how the dictionary reaches the spell checker, and
// `src/spelling.ts` for when.
//
// Generated from the schemas rather than kept by hand, because a key a schema
// gains is a word every package is about to be written in, and nobody would
// remember to add it here. `npm run cspell-dictionary` rewrites the file, and
// `src/test/suite/spelling.test.ts` fails while it is out of date.
//
// What is taken from a schema is every property name and every string an
// `enum` or a `const` allows, cut into the pieces the spell checker looks up:
// it splits `connectPorts` into `connect` and `Ports`, and a word at a digit, so
// `connectPorts` is no use to it as a word and `ports` is.

'use strict';

const fs = require('fs');
const path = require('path');

// Words that are PartCAD's but that no schema spells, because they are in the
// values a package writes rather than in its keys.
const EXTRA = [
    // PartCAD, and the tools and formats a package names.
    'partcad',
    'assy',
    'cadquery',
    'openscad',
    'freecad',
    'kicad',
    'gltf',
    'threejs',
    'urdf',
    'mjcf',
    'iges',
    'brep',
    'scad',
    'dxf',
    // Jinja2, which both languages are templates in.
    'jinja',
    'elif',
    'endfor',
    'endif',
    'endmacro',
    'endcall',
    'endfilter',
    'endset',
    'endblock',
    'endwith',
    'endraw',
    'endautoescape',
    'tojson',
    // What a template is rendered with: `param_<name>`, `partcad_version_at_least`.
    'param',
    'params',
];

const SCHEMAS = ['assy.json', 'partcad.json'];
const DEFAULT_SCHEMA_DIR = path.join(__dirname, '..', '..', '..', 'src', 'partcad_utils', 'schema');
const DICTIONARY = path.join(__dirname, 'partcad.txt');

/** The pieces of ``text`` the spell checker checks on their own: by case, and at anything not a letter. */
function pieces(text) {
    return text
        .split(/[^A-Za-z]+|(?<=[a-z])(?=[A-Z])|(?<=[A-Z])(?=[A-Z][a-z])/)
        .filter((piece) => piece.length >= 2)
        .map((piece) => piece.toLowerCase());
}

/** Every property name and allowed string in ``schema``, wherever it is. */
function spelled(schema, found) {
    if (Array.isArray(schema)) {
        schema.forEach((item) => spelled(item, found));
    } else if (schema && typeof schema === 'object') {
        for (const [key, value] of Object.entries(schema)) {
            if (key === 'properties' && value && typeof value === 'object' && !Array.isArray(value)) {
                Object.keys(value).forEach((name) => found.add(name));
            } else if (key === 'enum' && Array.isArray(value)) {
                value.filter((item) => typeof item === 'string').forEach((item) => found.add(item));
            } else if (key === 'const' && typeof value === 'string') {
                found.add(value);
            }
            spelled(value, found);
        }
    }
    return found;
}

/** The dictionary's words, sorted: the schemas' in ``schemaDir`` and the ones above. */
function dictionary(schemaDir = DEFAULT_SCHEMA_DIR) {
    const found = new Set(EXTRA);
    for (const name of SCHEMAS) {
        const schema = JSON.parse(fs.readFileSync(path.join(schemaDir, name), 'utf8'));
        for (const text of spelled(schema, new Set())) {
            pieces(text).forEach((piece) => found.add(piece));
        }
    }
    return [...found].sort();
}

/** The dictionary file's content. */
function render(words) {
    return (
        '# The words PartCAD writes ASSY files and package configurations in.\n' +
        '# Generated by cspell/generate.js from src/partcad_utils/schema -- do not edit.\n' +
        words.join('\n') +
        '\n'
    );
}

module.exports = { dictionary, render, DICTIONARY };

if (require.main === module) {
    fs.writeFileSync(DICTIONARY, render(dictionary()));
}
