authors:
  clairbee:
    name: Roman Kuzmenko
    description: Founder
    avatar: https://github.com/clairbee.png
  alexanderilyin:
    name: Aleksandr Ilin
    description: Co-Founder
    avatar: https://github.com/alexanderilyin.png
