[tool.bumpversion]
current_version = "0.7.118"
commit = "true"
commit_args = "--no-verify"
tag = "true"
tag_name = "{new_version}"
message = "Version updated from {current_version} to {new_version}"

[[tool.bumpversion.files]]
filename = "partcad/pyproject.toml"
search = "version = \"{current_version}\""
replace = "version = \"{new_version}\""

[[tool.bumpversion.files]]
filename = "partcad-cli/pyproject.toml"
search = "version = \"{current_version}\""
replace = "version = \"{new_version}\""

[[tool.bumpversion.files]]
filename = "partcad-cli/requirements.txt"
search = "partcad=={current_version}"
replace = "partcad=={new_version}"

[[tool.bumpversion.files]]
filename = "partcad/src/partcad/__init__.py"
search = "__version__: str = \"{current_version}\""
replace = "__version__: str = \"{new_version}\""

[[tool.bumpversion.files]]
filename = "partcad-cli/src/partcad_cli/__init__.py"
search = "__version__: str = \"{current_version}\""
replace = "__version__: str = \"{new_version}\""

[[tool.bumpversion.files]]
filename = "docs/mkdocs/docs/development/quick-start.md"
search = "Installing the current project: partcad-dev ({current_version})"
replace = "Installing the current project: partcad-dev ({new_version})"

[[tool.bumpversion.files]]
filename = "pyproject.toml"
search = "version = \"{current_version}\""
replace = "version = \"{new_version}\""

[[tool.bumpversion.files]]
filename = "examples/partcad.yaml"
search = "partcad: \">={current_version}\""
replace = "partcad: \">={new_version}\""

[[tool.bumpversion.files]]
filename = "partcad-ide-vscode/package.json"
search = "version\": \"{current_version}\""
replace = "version\": \"{new_version}\""

[[tool.bumpversion.files]]
filename = "partcad-ide-vscode/package.json"
search = "v{current_version} is not found"
replace = "v{new_version} is not found"

[[tool.bumpversion.files]]
filename = "partcad-ide-vscode/bundled/tool/lsp_server.py"
search = "version=\"{current_version}\""
replace = "version=\"{new_version}\""

[[tool.bumpversion.files]]
filename = "partcad-ide-vscode/bundled/tool/lsp_server.py"
search = "(\">={current_version}\")"
replace = "(\">={new_version}\")"

[[tool.bumpversion.files]]
filename = ".github/workflows/test.yml"
search = "VERSION: {current_version}"
replace = "VERSION: {new_version}"

[[tool.bumpversion.files]]
filename = ".github/workflows/test-dev.yml"
search = "VERSION: {current_version}"
replace = "VERSION: {new_version}"

[[tool.bumpversion.files]]
filename = ".devcontainer/devcontainer.json"
search = "devcontainer:{current_version}"
replace = "devcontainer:{new_version}"

[[tool.bumpversion.files]]
filename = ".devcontainer/Dockerfile"
search = "IMAGE_VERSION={current_version}"
replace = "IMAGE_VERSION={new_version}"

[[tool.bumpversion.files]]
filename = "tools/containers/python/Dockerfile"
search = "partcad-devcontainer:{current_version}"
replace = "partcad-devcontainer:{new_version}"
