#!/usr/bin/env python3
#
# PartCAD, 2026
#
# Licensed under Apache License, Version 2.0.
#
"""Every image an example's README points at has to be checked in.

The READMEs under 'examples/' are generated by 'pc render' out of the images
'pc render' leaves behind, and both are committed: that is what makes them a
regression canary, since a change in how PartCAD renders then shows up as a diff
instead of going unnoticed.

The failure that costs is the asymmetric one. A README is a tracked file, so
regenerating it stages itself with 'git add -u'; the images beside it are new
and untracked, so they do not. Commit that and the README on GitHub points at
images that are not there - which is how 'produce_part_brep/box.svg',
'produce_part_chili3d_primitive/cube.svg' and the six alias/enrich projections
of 'produce_part_cadquery_primitive' went missing, one PR at a time, without
anything going red.

Rendering every example takes tens of minutes, so the full "the tree is
unchanged after a render" check belongs in CI (see the 'Run: pc' job in
.github/workflows/test-dev.yml). This one is instant and catches the same
mistake at commit time. It also reports the other half of it: a '.gitignore'
entry naming an image the README does reference, or naming a file that no
example produces any more.
"""

from __future__ import annotations

import os
import re
import subprocess
import sys

EXAMPLES = "examples"

# The '<img src="...">' of a generated README. Local paths only: an example may
# also link a picture that lives on the web, and that is not ours to check.
IMG_SRC = re.compile(r'<img\s[^>]*?src="([^"]+)"', re.IGNORECASE)

# What 'pc render' can leave behind for a README to point at, which is the only
# thing this script has an opinion about.
IMAGE_EXTENSIONS = frozenset({".svg", ".png", ".jpg", ".jpeg"})


def as_git_path(path: str) -> str:
    """A local path in the form 'git ls-files' reports, so the two compare."""
    return path.replace(os.sep, "/")


def tracked_files(root: str) -> set:
    """Everything git knows about under 'root', as repo-relative paths."""
    out = subprocess.run(
        ["git", "ls-files", "-z", "--", root],
        check=True,
        capture_output=True,
        text=True,
    ).stdout
    return {path for path in out.split("\0") if path}


def readme_images(readme: str):
    """The local images that README references, as repo-relative paths."""
    with open(readme, "r", encoding="utf-8") as f:
        content = f.read()
    directory = os.path.dirname(readme)
    for src in IMG_SRC.findall(content):
        if src.startswith(("http://", "https://", "data:")):
            continue
        yield src, os.path.normpath(os.path.join(directory, src))


def stale_ignores(package_dir: str, referenced: set):
    """Entries of the package's '.gitignore' that are wrong or out of date.

    An entry is wrong when it hides an image the README points at, and out of
    date when it names an image that is not there. Both mean the ignore file has
    outlived the configuration it was written for.

    Only plain file names are looked at, and only images: a pattern says nothing
    about what exists, and a '.step' or a '.stl' entry is an export that is
    written on demand rather than something a render leaves behind.
    """
    path = os.path.join(package_dir, ".gitignore")
    if not os.path.exists(path):
        return
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            entry = line.strip()
            if not entry or entry.startswith("#") or any(c in entry for c in "*?[!/"):
                continue
            if os.path.splitext(entry)[1].lower() not in IMAGE_EXTENSIONS:
                continue
            target = os.path.join(package_dir, entry)
            if target in referenced:
                yield entry, "hides an image the README references"
            elif not os.path.exists(target):
                yield entry, "names an image nothing produces any more"


def main() -> int:
    if not os.path.isdir(EXAMPLES):
        print(f"{sys.argv[0]}: run me from the repository root", file=sys.stderr)
        return 2

    tracked = tracked_files(EXAMPLES)
    problems = []

    for directory, _dirs, files in os.walk(EXAMPLES):
        if "README.md" not in files:
            continue
        readme = os.path.join(directory, "README.md")
        referenced = set()
        for src, image in readme_images(readme):
            referenced.add(image)
            if not os.path.exists(image):
                problems.append(f"{readme}: references '{src}', which does not exist")
            elif as_git_path(image) not in tracked:
                problems.append(f"{readme}: references '{src}', which is not checked in")
        for entry, why in stale_ignores(directory, referenced):
            problems.append(f"{os.path.join(directory, '.gitignore')}: '{entry}' {why}")

    for problem in sorted(problems):
        print(problem)
    if problems:
        print(
            "\nRe-render the example ('cd examples/<package> && pc render') and commit"
            "\nthe images along with the README, or drop the stale '.gitignore' entry.",
        )
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
