name: "Setup CadQuery"
description: "Prepare CadQuery and its dependencies"

runs:
  using: "composite"
  steps:
      - name: Set CadQuery version
        shell: bash
        run: |
          echo "CADQUERY_VERSION=7.7.2" >> $GITHUB_ENV
          echo "CADQUERY_BASE_URL=https://github.com/jdegenstein/ocp-build-system/releases/download/7.7.2_macos_arm64" >> $GITHUB_ENV

      - name: install cadquery-ocp on MacOS
        if: ${{ startsWith(matrix.os, 'macos') && (matrix.os != 'macos-13') }}
        shell: bash
        run: |
          # shellcheck disable=SC1090
          . ~/.bashrc
          # shellcheck disable=SC1090
          . ~/.bash_profile

          PYTHON_VERSION="${{ matrix.python-version }}"
          PYTHON_VERSION_NO_DOT="${PYTHON_VERSION//./}"
          WHEEL_FILE="cadquery_ocp-${CADQUERY_VERSION}-cp${PYTHON_VERSION_NO_DOT}-cp${PYTHON_VERSION_NO_DOT}-macosx_11_0_arm64.whl"
          WHEEL_URL="${CADQUERY_BASE_URL}/${WHEEL_FILE}"

          for env in env-build env-build-cli env-test; do
            mamba activate $env
            python -m pip install "$WHEEL_URL"
            mamba deactivate
          done
