name: "Setup CadQuery"
description: "Prepare CadQuery and its dependencies"

runs:
  using: "composite"
  steps:

      # cadquery-ocp hack for MacOS with ARM
      - name: install cadquery-ocp on MacOS (Python 3.10)
        if: ${{ startsWith(matrix.os, 'macos') && (matrix.os != 'macos-13') && (matrix.python-version == '3.10') }}
        shell: bash
        run: |
          # shellcheck disable=SC1090
          . ~/.bashrc
          # shellcheck disable=SC1090
          . ~/.bash_profile

          mamba activate env-build
          python -m pip install https://github.com/jdegenstein/ocp-build-system/releases/download/7.7.2_macos_arm64/cadquery_ocp-7.7.2-cp310-cp310-macosx_11_0_arm64.whl
          mamba deactivate

          mamba activate env-build-cli
          python -m pip install https://github.com/jdegenstein/ocp-build-system/releases/download/7.7.2_macos_arm64/cadquery_ocp-7.7.2-cp310-cp310-macosx_11_0_arm64.whl
          mamba deactivate

          # Done in action.yml
          # mamba activate env-test
          # python -m pip install https://github.com/jdegenstein/ocp-build-system/releases/download/7.7.2_macos_arm64/cadquery_ocp-7.7.2-cp310-cp310-macosx_11_0_arm64.whl
          # mamba deactivate

      - name: install cadquery-ocp on MacOS (Python 3.11)
        if: ${{ startsWith(matrix.os, 'macos') && (matrix.os != 'macos-13') && (matrix.python-version == '3.11') }}
        shell: bash
        run: |
          # shellcheck disable=SC1090
          . ~/.bashrc
          # shellcheck disable=SC1090
          . ~/.bash_profile

          mamba activate env-build
          python -m pip install https://github.com/jdegenstein/ocp-build-system/releases/download/7.7.2_macos_arm64/cadquery_ocp-7.7.2-cp311-cp311-macosx_11_0_arm64.whl
          mamba deactivate

          mamba activate env-build-cli
          python -m pip install https://github.com/jdegenstein/ocp-build-system/releases/download/7.7.2_macos_arm64/cadquery_ocp-7.7.2-cp311-cp311-macosx_11_0_arm64.whl
          mamba deactivate

          # Done in action.yml
          mamba activate env-test
          python -m pip install https://github.com/jdegenstein/ocp-build-system/releases/download/7.7.2_macos_arm64/cadquery_ocp-7.7.2-cp311-cp311-macosx_11_0_arm64.whl
          mamba deactivate

      - name: install cadquery-ocp on MacOS (Python 3.12)
        if: ${{ startsWith(matrix.os, 'macos') && (matrix.os != 'macos-13') && (matrix.python-version == '3.12') }}
        shell: bash
        run: |
          # shellcheck disable=SC1090
          . ~/.bashrc
          # shellcheck disable=SC1090
          . ~/.bash_profile

          mamba activate env-build
          python -m pip install https://github.com/jdegenstein/ocp-build-system/releases/download/7.7.2_macos_arm64/cadquery_ocp-7.7.2-cp312-cp312-macosx_11_0_arm64.whl
          mamba deactivate

          mamba activate env-build-cli
          python -m pip install https://github.com/jdegenstein/ocp-build-system/releases/download/7.7.2_macos_arm64/cadquery_ocp-7.7.2-cp312-cp312-macosx_11_0_arm64.whl
          mamba deactivate

          # Done in action.yml
          mamba activate env-test
          python -m pip install https://github.com/jdegenstein/ocp-build-system/releases/download/7.7.2_macos_arm64/cadquery_ocp-7.7.2-cp312-cp312-macosx_11_0_arm64.whl
          mamba deactivate
