name: "Setup build environment"
description: "Prepare the runner to build"

runs:
  using: "composite"
  steps:
    ###################################################  PYTHON  ###################################################

    - name: Install prerequisites
      shell: bash -el {0}
      run: |
        conda create -n env-build python==${{ matrix.python-version }} -y
        conda activate env-build
        python -m ensurepip --upgrade
        python -m pip install --upgrade pip wheel mypy setuptools
        python -m pip install --upgrade build
        conda deactivate

        conda create -n env-build-cli python==${{ matrix.python-version }} -y
        conda activate env-build-cli
        python -m ensurepip --upgrade
        python -m pip install --upgrade pip wheel mypy setuptools
        python -m pip install --upgrade build
        conda deactivate

    #################################################  CADQUERY  ####################################################

    - name: Setup CadQuery
      uses: ./.github/actions/setup-cadquery
      with:
        envs: env-build env-build-cli
