name: "Setup build environment"
description: "Prepare the runner to build"

runs:
  using: "composite"
  steps:

    - name: Preinstall sdf (to avoid build isolation issues)
      shell: bash -el {0}
      run: |
        . ~/.bashrc
        . ~/.bash_profile
        mamba activate env-build-cli
        python -m pip install --no-build-isolation "sdf @ git+https://github.com/sasuke13/sdf.git"
        mamba deactivate

    ###################################################  PYTHON  ###################################################

    - name: Install prerequisites
      shell: bash -el {0}
      run: |
        . ~/.bashrc
        . ~/.bash_profile
        mamba create -n env-build python==${{ matrix.python-version }} -y
        mamba activate env-build
        python -m ensurepip --upgrade
        python -m pip install --upgrade pip wheel mypy setuptools
        python -m pip install --upgrade build
        mamba deactivate

        mamba create -n env-build-cli python==${{ matrix.python-version }} -y
        mamba activate env-build-cli
        python -m ensurepip --upgrade
        python -m pip install --upgrade pip wheel mypy setuptools
        python -m pip install --upgrade build
        mamba deactivate

    #################################################  CADQUERY  ####################################################

    - name: Setup CadQuery
      uses: ./.github/actions/setup-cadquery
      with:
        envs: env-build env-build-cli
