name: "Setup build environment"
description: "Prepare the runner to build"

runs:
  using: "composite"
  steps:

    ############################################## OS PREREQUISITES ################################################

    - name: Install prerequisites
      if: ${{ startsWith(matrix.os, 'ubuntu') }}
      shell: bash
      run: |
        sudo apt-get update || exit 1
        sudo apt-get install libcairo2-dev pkg-config python3-dev || exit 1

    - name: Install prerequisites
      shell: bash
      run: |
        # shellcheck disable=SC1090
        . ~/.bashrc
        # shellcheck disable=SC1090
        . ~/.bash_profile

        mamba create -n env-build python=${{ matrix.python-version }} -y
        mamba activate env-build
        python -m ensurepip --upgrade
        python -m pip install --upgrade pip wheel mypy setuptools
        python -m pip install --upgrade build
        mamba deactivate

        mamba create -n env-build-cli python=${{ matrix.python-version }} -y
        mamba activate env-build-cli
        python -m ensurepip --upgrade
        python -m pip install --upgrade pip wheel mypy setuptools
        python -m pip install --upgrade build
        mamba deactivate

        # Done in action.yml
        # mamba create -n env-test python=${{ matrix.python-version }} -y
        # mamba activate env-test
        # python -m pip install --upgrade build
        # mamba deactivate

    #################################################  CADQUERY  ####################################################

    - name: Set CadQuery version
      shell: bash
      run: |
        echo "CADQUERY_VERSION=7.7.2" >> $GITHUB_ENV
        echo "CADQUERY_BASE_URL=https://github.com/jdegenstein/ocp-build-system/releases/download/7.7.2_macos_arm64" >> $GITHUB_ENV

    - name: install cadquery-ocp on MacOS
      if: ${{ startsWith(matrix.os, 'macos') && (matrix.os != 'macos-13') }}
      shell: bash
      run: |
        # shellcheck disable=SC1090
        . ~/.bashrc
        # shellcheck disable=SC1090
        . ~/.bash_profile

        PYTHON_VERSION="${{ matrix.python-version }}"
        PYTHON_VERSION_NO_DOT="${PYTHON_VERSION//./}"
        WHEEL_FILE="cadquery_ocp-${CADQUERY_VERSION}-cp${PYTHON_VERSION_NO_DOT}-cp${PYTHON_VERSION_NO_DOT}-macosx_11_0_arm64.whl"
        WHEEL_URL="${CADQUERY_BASE_URL}/${WHEEL_FILE}"

        for env in env-build env-build-cli env-test; do
          mamba activate $env
          python -m pip install "$WHEEL_URL"
          mamba deactivate
        done
