name: "Setup all"
description: "Prepare the runner to build"

runs:
  using: "composite"
  steps:
    - uses: ./.github/actions/setup-all/10-prereqs.yml
    - uses: ./.github/actions/setup-all/20-cadquery.yml
