#
# PartCAD, 2026
#
# Licensed under Apache License, Version 2.0.
#

"""A renderer-independent model of a generated document.

The same document is asked for in more than one shape: the markdown bill of
materials of an assembly ('pc render -t readme'), the PDF assembly instruction
book ('-t pdf') and the HTML one ('-t html') all say the same things about the
same assembly, and only differ in how they are written down. What they say is
built once (see assembly_guide.py) as the blocks below, and each output format
is a function of that model - so a change to what a document says lands in all
three at once, and a change to how one of them looks cannot silently make the
three disagree.

A document is a list of pages. Only the paginated formats treat a page as a
physical page: markdown concatenates them, and HTML shows one at a time. A page
whose content does not fit is continued on the next physical page by the PDF
renderer, so a page here means "a new page starts here", not "everything here
fits on one".
"""

import base64
import html
import json
import mimetypes
import os
import re
from dataclasses import dataclass, field
from typing import Optional

PARTCAD_URL = "https://partcad.org/"
GENERATED_BY = "Generated by [PartCAD](%s)" % PARTCAD_URL

# The one piece of markdown the model itself carries (see '_html_inline').
_MARKDOWN_LINK = re.compile(r"\[([^\]]*)\]\(([^)]*)\)")

# The size the markdown documents have always given a shape's projection.
MARKDOWN_IMAGE_STYLE = "width: auto; height: auto; max-width: 200px; max-height: 200px;"


@dataclass
class Image:
    """A picture, addressed both as a file and as a link.

    'file' is where the image is on this machine (used by the renderers that
    embed it), 'src' is what a document that merely points at it has to write
    (used by markdown, which stays next to the file it refers to). A document
    that renders its images into a temporary directory has no meaningful 'src'
    and leaves it unset.
    """

    file: Optional[str] = None
    src: Optional[str] = None
    alt: str = ""
    caption: Optional[str] = None


@dataclass
class Block:
    """Base class of everything a page is made of."""


@dataclass
class Heading(Block):
    text: str
    level: int = 1
    url: Optional[str] = None


@dataclass
class Paragraph(Block):
    text: str


@dataclass
class Properties(Block):
    """Short "label: value" metadata, e.g. the author of a package."""

    items: list = field(default_factory=list)


@dataclass
class ImageRow(Block):
    """One or more images shown side by side.

    'height' is the fraction of the page the row is given by the paginated
    renderers; the images keep their aspect ratio within it.
    """

    images: list = field(default_factory=list)
    height: float = 0.4


@dataclass
class Table(Block):
    columns: list = field(default_factory=list)
    rows: list = field(default_factory=list)
    # "left" or "right", per column; defaults to all-left.
    aligns: Optional[list] = None


@dataclass
class LinkList(Block):
    """A list of (text, url) pairs."""

    items: list = field(default_factory=list)


@dataclass
class Page:
    blocks: list = field(default_factory=list)
    # Shown in the navigation of the formats that have any; never rendered as
    # content, so a page that starts with a heading is not titled twice.
    title: Optional[str] = None


@dataclass
class Document:
    title: str = ""
    subtitle: Optional[str] = None
    pages: list = field(default_factory=list)
    footer: Optional[str] = None


def _aligns(table: Table):
    return table.aligns or ["left"] * len(table.columns)


def _table_cell(text):
    """A value made safe to put in one cell of a markdown table."""
    text = "" if text is None else str(text)
    return text.replace("|", "\\|").replace("\n", "<br/>")


def render_markdown(document: Document) -> list:
    """The document as markdown, one list entry per line.

    Pages are concatenated: markdown has no pages, and the reader of a bill of
    materials scrolls rather than flips.
    """
    lines = []

    for page in document.pages:
        for block in page.blocks:
            lines += _markdown_block(block)

    if document.footer:
        lines += ["<br/><br/>", "", "*%s*" % document.footer]

    return lines


def _markdown_block(block: Block) -> list:
    if isinstance(block, Heading):
        text = block.text if block.url is None else "[%s](%s)" % (block.text, block.url)
        return ["#" * block.level + " " + text, ""]

    if isinstance(block, Paragraph):
        return [block.text, ""]

    if isinstance(block, Properties):
        return ["%s: %s" % (label, value) for label, value in block.items] + [""]

    if isinstance(block, ImageRow):
        lines = []
        for image in block.images:
            lines += ['<img src="%s" alt="%s" style="%s">' % (image.src or image.file, image.alt, MARKDOWN_IMAGE_STYLE)]
            if image.caption:
                lines += ["", image.caption]
        return lines + [""]

    if isinstance(block, Table):
        aligns = _aligns(block)
        lines = ["| " + " | ".join(block.columns) + " |"]
        lines += ["| " + " | ".join("---:" if align == "right" else "---" for align in aligns) + " |"]
        for row in block.rows:
            lines += ["| " + " | ".join(_table_cell(cell) for cell in row) + " |"]
        return lines + [""]

    if isinstance(block, LinkList):
        return ["- [%s](%s)" % (text, url) for text, url in block.items] + [""]

    raise TypeError("Unsupported document block: %s" % type(block).__name__)


def _html_inline(text: str) -> str:
    """A short piece of text as HTML, with its markdown links turned into anchors.

    The few strings the model carries as markdown - the footer - say the same
    thing in every format, so they are written once and translated here rather
    than kept in two spellings.
    """
    parts = []
    position = 0
    for match in _MARKDOWN_LINK.finditer(text):
        parts.append(html.escape(text[position : match.start()]))
        parts.append('<a href="%s">%s</a>' % (html.escape(match.group(2), quote=True), html.escape(match.group(1))))
        position = match.end()
    parts.append(html.escape(text[position:]))
    return "".join(parts)


def _image_source(image: Image) -> Optional[str]:
    """What an HTML document should put in 'src' for this image.

    The file is inlined when it is available: an assembly guide is one file that
    gets mailed around, and a picture that lives next to it on the machine that
    generated it does not survive that trip.
    """
    if image.file and os.path.exists(image.file):
        mime = mimetypes.guess_type(image.file)[0] or "application/octet-stream"
        with open(image.file, "rb") as f:
            payload = base64.b64encode(f.read()).decode("ascii")
        return "data:%s;base64,%s" % (mime, payload)
    return image.src


def render_html(document: Document) -> str:
    """The document as a single self-contained HTML file.

    One page is shown at a time, laid out like a page of the PDF, with arrows on
    either side to flip through the guide.
    """
    # The footer belongs to the page, not to the document: every page of the PDF
    # carries it, and a page here is a page there.
    footer = ""
    if document.footer:
        footer = '\n<div class="footer">%s</div>' % _html_inline(document.footer)

    pages_html = []
    for number, page in enumerate(document.pages, start=1):
        blocks = "\n".join(_html_block(block) for block in page.blocks)
        pages_html.append(
            '<section class="page" id="page-%d" data-title="%s">\n%s%s\n</section>'
            % (number, html.escape(page.title or ""), blocks, footer)
        )

    # json.dumps, not hand-escaping: these become JavaScript string literals, and
    # HTML escaping leaves a backslash in a title alone - which would end the
    # literal in the wrong place and take the whole script with it.
    titles = [json.dumps(page.title or "") for page in document.pages]

    return _HTML_TEMPLATE % {
        "title": html.escape(document.title),
        "pages": "\n".join(pages_html),
        "titles": ", ".join(titles),
    }


def _html_block(block: Block) -> str:
    if isinstance(block, Heading):
        level = min(max(block.level, 1), 6)
        text = html.escape(block.text)
        if block.url:
            text = '<a href="%s">%s</a>' % (html.escape(block.url, quote=True), text)
        return "<h%d>%s</h%d>" % (level, text, level)

    if isinstance(block, Paragraph):
        return "<p>%s</p>" % html.escape(block.text).replace("\n", "<br/>")

    if isinstance(block, Properties):
        items = "".join(
            "<dt>%s</dt><dd>%s</dd>" % (html.escape(str(label)), html.escape(str(value)))
            for label, value in block.items
        )
        return '<dl class="properties">%s</dl>' % items

    if isinstance(block, ImageRow):
        figures = []
        for image in block.images:
            source = _image_source(image)
            if source is None:
                continue
            caption = ""
            if image.caption:
                caption = "<figcaption>%s</figcaption>" % html.escape(image.caption)
            figures.append(
                '<figure><img src="%s" alt="%s"/>%s</figure>'
                % (html.escape(source, quote=True), html.escape(image.alt, quote=True), caption)
            )
        if not figures:
            return ""
        return '<div class="images" style="flex-basis: %d%%">%s</div>' % (
            int(round(block.height * 100)),
            "".join(figures),
        )

    if isinstance(block, Table):
        aligns = _aligns(block)
        head = "".join(
            '<th style="text-align: %s">%s</th>' % (align, html.escape(str(column)))
            for column, align in zip(block.columns, aligns)
        )
        body = []
        for row in block.rows:
            # A row with more cells than there are columns keeps them all, the
            # same way markdown does: the three formats have to say the same
            # thing about the same document.
            row_aligns = list(aligns) + ["left"] * max(0, len(row) - len(aligns))
            cells = "".join(
                '<td style="text-align: %s">%s</td>' % (align, html.escape("" if cell is None else str(cell)))
                for cell, align in zip(row, row_aligns)
            )
            body.append("<tr>%s</tr>" % cells)
        return "<table><thead><tr>%s</tr></thead><tbody>%s</tbody></table>" % (head, "".join(body))

    if isinstance(block, LinkList):
        items = "".join(
            '<li><a href="%s">%s</a></li>' % (html.escape(url, quote=True), html.escape(text))
            for text, url in block.items
        )
        return '<ul class="links">%s</ul>' % items

    raise TypeError("Unsupported document block: %s" % type(block).__name__)


def to_data(document: Document) -> dict:
    """The document as plain data, for a renderer that runs somewhere else.

    The PDF is composed in a sandboxed runtime (that is where the libraries that
    can draw one are), and only plain data crosses that boundary.
    """
    return {
        "title": document.title,
        "subtitle": document.subtitle,
        "footer": document.footer,
        "pages": [
            {
                "title": page.title,
                "blocks": [_block_to_data(block) for block in page.blocks],
            }
            for page in document.pages
        ],
    }


def _block_to_data(block: Block) -> dict:
    if isinstance(block, Heading):
        return {"type": "heading", "text": block.text, "level": block.level, "url": block.url}
    if isinstance(block, Paragraph):
        return {"type": "paragraph", "text": block.text}
    if isinstance(block, Properties):
        return {"type": "properties", "items": [list(item) for item in block.items]}
    if isinstance(block, ImageRow):
        return {
            "type": "images",
            "height": block.height,
            "images": [
                {"path": image.file, "caption": image.caption, "alt": image.alt} for image in block.images if image.file
            ],
        }
    if isinstance(block, Table):
        return {
            "type": "table",
            "columns": list(block.columns),
            "aligns": _aligns(block),
            "rows": [["" if cell is None else str(cell) for cell in row] for row in block.rows],
        }
    if isinstance(block, LinkList):
        return {"type": "links", "items": [list(item) for item in block.items]}
    raise TypeError("Unsupported document block: %s" % type(block).__name__)


_HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<meta name="generator" content="PartCAD"/>
<title>%(title)s</title>
<style>
:root { color-scheme: light dark; --fg: #1c1c1c; --bg: #f2f2f2; --paper: #ffffff; --muted: #666666; --line: #dddddd; }
@media (prefers-color-scheme: dark) {
  :root { --fg: #e6e6e6; --bg: #16181a; --paper: #202325; --muted: #a0a0a0; --line: #3a3d40; }
}
* { box-sizing: border-box; }
body { margin: 0; padding: 0; background: var(--bg); color: var(--fg);
       font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; }
main { display: flex; align-items: center; justify-content: center; min-height: 100vh; padding: 24px 64px; }
.page { display: none; flex-direction: column; background: var(--paper); color: var(--fg);
        width: 100%%; max-width: 210mm; min-height: 297mm; padding: 16mm; box-shadow: 0 1px 8px rgba(0,0,0,.2); }
.page.current { display: flex; }
h1 { font-size: 2rem; margin: 0 0 .6em 0; }
h2 { font-size: 1.4rem; margin: 1em 0 .4em 0; }
h3 { font-size: 1.1rem; margin: 1em 0 .4em 0; }
p { line-height: 1.5; }
a { color: inherit; }
.properties { display: grid; grid-template-columns: max-content 1fr; gap: 2px 12px; margin: 1em 0; color: var(--muted); }
.properties dt { font-weight: 600; }
.properties dd { margin: 0; }
.images { display: flex; gap: 16px; align-items: center; justify-content: center; margin: 12px 0; }
.images figure { margin: 0; flex: 1 1 0; text-align: center; min-width: 0; }
.images img { max-width: 100%%; max-height: 60vh; height: auto; }
figcaption { color: var(--muted); font-size: .85rem; margin-top: 6px; }
table { border-collapse: collapse; width: 100%%; margin: 8px 0 16px 0; font-size: .9rem; }
th, td { border-bottom: 1px solid var(--line); padding: 4px 8px; }
ul.links { line-height: 1.8; }
.footer { margin-top: auto; padding-top: 16px; color: var(--muted); font-size: .8rem; text-align: center; }
.nav { position: fixed; top: 0; height: 100%%; width: 56px; border: none; background: transparent;
       color: var(--muted); font-size: 2rem; cursor: pointer; }
.nav:hover { color: var(--fg); background: rgba(127,127,127,.08); }
.nav[disabled] { opacity: .2; cursor: default; }
#prev { left: 0; }
#next { right: 0; }
#counter { position: fixed; bottom: 12px; left: 50%%; transform: translateX(-50%%);
           color: var(--muted); font-size: .8rem; }
@media print {
  .nav, #counter { display: none; }
  .page { display: flex; box-shadow: none; break-after: page; min-height: auto; }
}
</style>
</head>
<body>
<button class="nav" id="prev" title="Previous page (left arrow)">&#8249;</button>
<main>
%(pages)s
</main>
<button class="nav" id="next" title="Next page (right arrow)">&#8250;</button>
<div id="counter"></div>
<script>
(function () {
  var pages = Array.prototype.slice.call(document.querySelectorAll(".page"));
  var titles = [%(titles)s];
  var prev = document.getElementById("prev");
  var next = document.getElementById("next");
  var counter = document.getElementById("counter");
  var current = 0;

  function show(index, updateHash) {
    current = Math.min(Math.max(index, 0), pages.length - 1);
    pages.forEach(function (page, i) { page.classList.toggle("current", i === current); });
    prev.disabled = current === 0;
    next.disabled = current === pages.length - 1;
    counter.textContent = (current + 1) + " / " + pages.length + (titles[current] ? " \\u2014 " + titles[current] : "");
    if (updateHash !== false) { history.replaceState(null, "", "#page-" + (current + 1)); }
    window.scrollTo(0, 0);
  }

  function fromHash() {
    var match = /^#page-(\\d+)$/.exec(window.location.hash);
    show(match ? parseInt(match[1], 10) - 1 : 0, false);
  }

  prev.addEventListener("click", function () { show(current - 1); });
  next.addEventListener("click", function () { show(current + 1); });
  window.addEventListener("keydown", function (event) {
    if (event.key === "ArrowLeft" || event.key === "PageUp") { show(current - 1); }
    if (event.key === "ArrowRight" || event.key === "PageDown" || event.key === " ") { show(current + 1); }
    if (event.key === "Home") { show(0); }
    if (event.key === "End") { show(pages.length - 1); }
  });
  window.addEventListener("hashchange", fromHash);
  fromHash();
})();
</script>
</body>
</html>
"""
