[tool.bumpversion]
current_version = "0.7.39"
commit = "true"
commit_args = "--no-verify"
tag = "true"
tag_name = "{new_version}"
message = "Version updated from {current_version} to {new_version}"

[[tool.bumpversion.files]]
filename = "partcad/pyproject.toml"
search = "version = \"{current_version}\""
replace = "version = \"{new_version}\""

[[tool.bumpversion.files]]
filename = "partcad-cli/pyproject.toml"
search = "version = \"{current_version}\""
replace = "version = \"{new_version}\""

[[tool.bumpversion.files]]
filename = "partcad-cli/requirements.txt"
search = "partcad=={current_version}"
replace = "partcad=={new_version}"

[[tool.bumpversion.files]]
filename = "partcad/src/partcad/__init__.py"
search = "__version__: str = \"{current_version}\""
replace = "__version__: str = \"{new_version}\""

[[tool.bumpversion.files]]
filename = "partcad-cli/src/partcad_cli/__init__.py"
search = "__version__: str = \"{current_version}\""
replace = "__version__: str = \"{new_version}\""

[[tool.bumpversion.files]]
filename = "partcad-ide-vscode/package.json"
search = "version\": \"{current_version}\""
replace = "version\": \"{new_version}\""

[[tool.bumpversion.files]]
filename = "partcad-ide-vscode/package.json"
search = "v{current_version} is not found"
replace = "v{new_version} is not found"

[[tool.bumpversion.files]]
filename = "partcad-ide-vscode/bundled/tool/lsp_server.py"
search = "version=\"{current_version}\""
replace = "version=\"{new_version}\""

[[tool.bumpversion.files]]
filename = "partcad-ide-vscode/bundled/tool/lsp_server.py"
search = "(>={current_version})"
replace = "(>={new_version})"
