name: "Setup all"
description: "Prepare the runner no matter what the job is"

inputs:
  job:
    description: "The name of the job calling this action"
    default: "default"

runs:
  using: "composite"
  steps:
    ############################################## OS PREREQUISITES ################################################

    # TODO(clairbee): minimize these pre-requisites by moving the VSCode build job away from the test workflow (ci.yml)
    - name: Install prerequisites
      if: ${{ startsWith(matrix.os, 'ubuntu') }}
      shell: bash -el {0}
      run: |
        sudo apt-get -q update || exit 1
        sudo apt-get -q install -y \
          nodejs npm \
          libtiff5-dev libjpeg-dev libopenjp2-7-dev zlib1g-dev \
          libfreetype6-dev liblcms2-dev libwebp-dev tcl8.6-dev tk8.6-dev \
          python3-tk libharfbuzz-dev libfribidi-dev libxcb1-dev \
          libxml2-dev libxslt-dev \
          libcairo2-dev pkg-config python3-dev \
            || exit 1

    - name: Install prerequisites
      if: ${{ startsWith(matrix.os, 'macos') }}
      shell: bash -el {0}
      run: |
        HOMEBREW_NO_AUTO_UPDATE=1 brew install jpeg

    - name: Install prerequisites
      if: ${{ startsWith(matrix.os, 'windows') }}
      shell: bash -el {0}
      run: |
        vcpkg.exe install zlib
    #     vcpkg.exe install pkgconf
    #     vcpkg.exe install freetype
    #     vcpkg.exe install cairo
    #     choco uninstall StrawberryPerl -y
    #     # choco install pkgconfiglite
    #     choco install pacman
    #     pacman -Sy pkgconf

    ###################################################  PYTHON  ###################################################

    # Miniconda
    - name: Cache conda
      uses: actions/cache@v4
      env:
        # Increase this value to reset cache if etc/example-environment.yml has not changed
        CACHE_NUMBER: 3
      with:
        enableCrossOsArchive: true
        # path: ~/conda_pkgs_dir
        path: ${{ runner.os == 'Windows' && 'D:\\conda_pkgs_dir' || '~/conda_pkgs_dir' }}
        key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}

    - uses: conda-incubator/setup-miniconda@v3
      continue-on-error: true # Usually it fails while setting up the unwanted 'test' environment
      with:
        miniforge-version: 24.11.3-0
        channels: conda-forge,defaults
        channel-priority: flexible
        python-version: ${{ matrix.python-version }}
        # conda-solver: classic
        # activate-environment: env
        auto-activate-base: false
        auto-update-conda: true
        use-only-tar-bz2: true
        # pkgs-dirs: ~/conda_pkgs_dir
        pkgs-dirs: ${{ runner.os == 'Windows' && format('D:\\conda_pkgs_dir_{0}', matrix.python-version) || format('~/conda_pkgs_dir_{0}', matrix.python-version) }}
        # pkgs-dirs: ${{ format('~/conda_pkgs_dir_{0}', matrix.python-version) }}

    # - uses: mamba-org/setup-micromamba@v2
    #   with:
    #     micromamba-version: 2.0.5-0
    #     # environment-file: environment.yml
    #     init-shell: >-
    #       bash
    #       powershell
    #     # cache-environment: true
    #     post-cleanup: "all"

    # - name: Init conda
    #   shell: bash
    #   run: |
    #     touch ~/.bashrc
    #     touch ~/.bash_profile
    #     . ~/.bashrc
    #     . ~/.bash_profile
    #     conda init

    # - uses: actions/cache@v4
    #   id: cache
    #   with:
    #     path: ~/.cache/pip
    #     key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.*') }}
    #     restore-keys: |
    #       ${{ runner.os }}-pip-

    # TODO(clairbee): Cache conda packages
    # TODO(clairbee): Cache the conda environment?

    # Install dev dependencies
    - name: install dev dependencies
      shell: bash -el {0}
      env:
        ENV_PATH: ~/${{ format('env-test-{0}-{1}', inputs.job, matrix.python-version) }}
      run: |
        # . ~/.bashrc
        # . ~/.bash_profile
        # conda clean --all
        # conda clean -y -i
        conda create -p $ENV_PATH python=${{ matrix.python-version }} -y
        conda activate $ENV_PATH
        conda install -p $ENV_PATH --yes pip wheel mypy setuptools
        # Install all core and a subset of CLI dependencies, that are required for tests
        conda install -p $ENV_PATH --yes --file partcad/requirements.txt
        conda install -p $ENV_PATH --yes --file partcad/requirements-dev.in
        conda install -p $ENV_PATH --yes --file partcad-ide-vscode/src/test/python_tests/requirements.txt
        conda deactivate

        # echo "PC_INTERNAL_STATE_DIR=$(mktemp -d)" >> $GITHUB_ENV

    # - name: Update Homebrew
    #   if: matrix.os == 'macos-latest'
    #   shell: bash
    #   run: |
    #     brew update --preinstall
    #     # cat "$(brew --repository)/Library/Taps/homebrew/homebrew-core/Formula/nlopt.rb" > .github/brew-formulae
    # # - name: Configure Homebrew cache
    # #   if: matrix.os == 'macos-latest'
    # #   uses: actions/cache@v2
    # #   with:
    # #     path: |
    # #       ~/Library/Caches/Homebrew/nlopt--*
    # #       ~/Library/Caches/Homebrew/downloads/*--nlopt-*
    # #     key: brew-${{ hashFiles('.github/brew-formulae') }}
    # #     restore-keys: brew-
    # - name: Install Homebrew dependencies
    #   if: matrix.os == 'macos-latest'
    #   shell: bash
    #   run: |
    #     # env HOMEBREW_NO_AUTO_UPDATE=1 brew install nlopt
    #     HOMEBREW_NO_AUTO_UPDATE=1 brew install gcc
    #     HOMEBREW_NO_AUTO_UPDATE=1 brew install nlopt
