name: "Setup prerequisites"
description: "Prepare OS packages"

runs:
  using: "composite"
  steps:

      - name: Install prerequisites
        shell: bash
        run: |
          # shellcheck disable=SC1090
          . ~/.bashrc
          # shellcheck disable=SC1090
          . ~/.bash_profile

          mamba create -n test python=${{ matrix.python-version }} -y
          mamba activate test
          python -m pip install --upgrade pip
          pip install -U pytest
          # Install all core and a subset of CLI dependencies, that are required for tests
          pip install -r partcad/requirements.txt && pip install svglib rlPyCairo renderlab
          pip install -r partcad/requirements-dev.in
          mamba deactivate
