name: "Setup CadQuery"
description: "Prepare CadQuery and its dependencies"

runs:
  using: "composite"
  steps:

    # cadquery-ocp hack for macOS with ARM
    - name: install macos dev dependencies
      if: startsWith(${{matrix.os}}, 'macos')
      shell: bash
      run: |
        . ~/.bashrc
        . ~/.bash_profile
        mamba activate env-test
        pip install swig
        mamba deactivate

    - name: install cadquery-ocp on macOS
      if: ${{ startsWith(matrix.os, 'macos') && (matrix.os != 'macos-13') }}
      shell: bash
      run: |
        . ~/.bashrc
        . ~/.bash_profile
        mamba activate env-test

        VERSION="7.7.2"
        PY_VERSION="${{ matrix.python-version }}"
        PY_VERSION_NO_DOT="${PY_VERSION//./}"
        WHEEL_URL="https://github.com/jdegenstein/ocp-build-system/releases/download/${VERSION}_macos_arm64/cadquery_ocp-${VERSION}-cp${PY_VERSION_NO_DOT}-cp${PY_VERSION_NO_DOT}-macosx_11_0_arm64.whl"
        WHEEL_FILE="cadquery_ocp-${VERSION}-cp${PY_VERSION_NO_DOT}-cp${PY_VERSION_NO_DOT}-macosx_11_0_arm64.whl"

        # Download wheel
        curl -L -o "$WHEEL_FILE" "$WHEEL_URL"

        pip install "$WHEEL_FILE"
        mamba deactivate
