name: "Setup CadQuery"
description: "Prepare CadQuery and its dependencies"

runs:
  using: "composite"
  steps:

    # cadquery-ocp hack for macOS with ARM
    - name: install macos dev dependencies
      if: startsWith(${{matrix.os}}, 'macos')
      shell: bash
      run: |
        . ~/.bashrc
        . ~/.bash_profile
        mamba activate env-test
        pip install swig
        mamba deactivate

    - name: install cadquery-ocp on macOS (Python 3.10)
      if: ${{ startsWith(matrix.os, 'macos') && (matrix.os != 'macos-13') && (matrix.python-version == '3.10') }}
      shell: bash
      run: |
        . ~/.bashrc
        . ~/.bash_profile
        mamba activate env-test
        pip install https://github.com/jdegenstein/ocp-build-system/releases/download/7.7.2_macos_arm64/cadquery_ocp-7.7.2-cp310-cp310-macosx_11_0_arm64.whl
        mamba deactivate

    - name: install cadquery-ocp on macOS (Python 3.11)
      if: ${{ startsWith(matrix.os, 'macos') && (matrix.os != 'macos-13') && (matrix.python-version == '3.11') }}
      shell: bash
      run: |
        . ~/.bashrc
        . ~/.bash_profile
        mamba activate env-test
        pip install https://github.com/jdegenstein/ocp-build-system/releases/download/7.7.2_macos_arm64/cadquery_ocp-7.7.2-cp311-cp311-macosx_11_0_arm64.whl
        mamba deactivate

    - name: install cadquery-ocp on macOS (Python 3.12)
      if: ${{ startsWith(matrix.os, 'macos') && (matrix.os != 'macos-13') && (matrix.python-version == '3.12') }}
      shell: bash
      run: |
        . ~/.bashrc
        . ~/.bash_profile
        mamba activate env-test
        pip install https://github.com/jdegenstein/ocp-build-system/releases/download/7.7.2_macos_arm64/cadquery_ocp-7.7.2-cp312-cp312-macosx_11_0_arm64.whl
        mamba deactivate
