name: "Setup OpenSCAD"
description: "Prepare OpenSCAD"

runs:
  using: "composite"
  steps:

      - name: Install OpenSCAD (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y openscad

      - name: Install OpenSCAD (macOS)
        if: runner.os == 'macOS'
        run: |
          brew install -f openscad || ( \
            rm /Users/runner/Library/Caches/Homebrew/downloads/*--OpenSCAD-*.dmg && brew install -f openscad)

      - name: Install OpenSCAD (Windows)
        if: runner.os == 'Windows'
        run: .github/scripts/openscad.ps1
        timeout-minutes: 1
