name: "Setup all"
description: "Prepare the runner to test"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/setup-test/10-prereqs.yml
    - uses: ./.github/actions/setup-test/20-cadquery.yml
    - uses: ./.github/actions/setup-test/30-openscad.yml
    - uses: ./.github/actions/setup-test/70-registry.yml
