name: "Setup all"
description: "Prepare the runner to test"

inputs:
  job:
    description: "The name of the job calling this action"
    default: "default"

runs:
  using: "composite"
  steps:
    #################################################  CADQUERY  ####################################################

    - name: Setup CadQuery
      uses: ./.github/actions/setup-cadquery
      with:
        envs: ${{ format('env-test-{0}-{1}', env.INPUT_JOB, matrix.python-version) }}

    #################################################  OPENSCAD  ####################################################

    - name: Install OpenSCAD (Linux)
      if: runner.os == 'Linux'
      shell: bash -l {0}
      run: |
        sudo apt-get update
        sudo apt-get install -y openscad

    - name: Install OpenSCAD (macOS)
      if: runner.os == 'macOS'
      shell: bash -l {0}
      run: |
        # The below "rm" command does not have "-f" on purpose:
        # the second "brew install" command is only needed when the dmg file is psesent but corrupted
        which openscad \
          || HOMEBREW_NO_AUTO_UPDATE=1 brew install -f openscad \
          || ( \
            rm /Users/$USER/Library/Caches/Homebrew/downloads/*--OpenSCAD-*.dmg \
            && HOMEBREW_NO_AUTO_UPDATE=1 brew install -f openscad \
          )

    - name: Install OpenSCAD (Windows)
      if: runner.os == 'Windows'
      shell: powershell
      run: .github/actions/setup-test/openscad.ps1

    #################################################  REGISTRY  ####################################################

    - name: Fix Windows registry
      if: runner.os == 'Windows'
      shell: powershell
      run: .github/actions/setup-test/registry.ps1

    #################################################  GIT SETUP  ###################################################

    - name: Configure Git
      shell: bash -l {0}
      run: |
        # TODO(clairbee): Switch to SSH for most of jobs, but not for all of them
        # git config --global url."git@github.com:".insteadOf "https://github.com/"
        git config --global protocol.version 2
