@cli @pc-filter
Feature: `pc filter` command

  # A second assembly made of some of the first one's links. What a filter is is
  # written down once -- docs/source/assy.rst, over
  # 'partcad_utils.assy_filter' -- and read by three things that have to agree:
  # this command, 'pc render --filter'/'pc export --filter', and the panel beside
  # the IDE's 2D and Draft tabs. What this feature covers is the half that is
  # this command's own: the file it writes, the declaration it adds, and the one
  # thing filtering can break.

  Background: A package with an assembly and a scene to select from
    Given I am in "/tmp/sandbox/behave" directory
    And I have temporary $HOME in "/tmp/sandbox/home"
    And a file named "partcad.yaml" with content
      """
      parts:
        cube:
          type: cadquery
          path: cube.py

      assemblies:
        widget:
          type: assy
          desc: A base, a tower of two cubes, and a pin

      scenes:
        table:
          type: assy
      """
    And a file named "cube.py" with content
      """
      import cadquery as cq

      show_object(cq.Workplane("XY").box(10, 10, 10))
      """
    And a file named "widget.assy" with content
      """
      # What the widget is.
      links:
        - part: cube
          name: base
          location: [[0, 0, 0], [0, 0, 1], 0]
        - name: tower
          links:
            - part: cube
              name: lower
              location: [[0, 0, 10], [0, 0, 1], 0]
            - part: cube
              name: upper
              location: [[0, 0, 20], [0, 0, 1], 0]
      """
    And a file named "table.assy" with content
      """
      links:
        - part: cube
          name: block
          location: [[0, 0, 0], [0, 0, 1], 0]
        - part: cube
          name: post
          location: [[30, 0, 0], [0, 0, 1], 0]
      """

  @success
  Scenario: A filter written on the command line
    When I run "pc --no-ansi filter '{base: null}' widget widget_base"
    Then the command should exit with a status code of "0"
    And STDERR should contain "Created the assembly 'widget_base' from 'widget'"
    And a file named "widget_base.assy" should exist
    And a file named "widget_base.assy" should contain "name: base"
    And a file named "widget_base.assy" should not contain "name: tower"
    # Generated, and it says so: re-running the command is how it is changed.
    And a file named "widget_base.assy" should contain "Generated by 'pc filter'"
    # The comments of the file somebody wrote survive, because the document is
    # filtered rather than written afresh.
    And a file named "widget_base.assy" should contain "What the widget is."
    And a file named "partcad.yaml" should contain "widget_base:"

  @success
  Scenario: The new object is one every other command works on
    When I run "pc --no-ansi filter '[base]' widget widget_base"
    Then the command should exit with a status code of "0"
    When I run "pc --no-ansi bom widget_base"
    Then the command should exit with a status code of "0"
    And STDERR should contain "//:cube"

  @success
  Scenario: A link named with children keeps those children only
    When I run "pc --no-ansi filter '{tower: {upper: null}}' widget widget_top"
    Then the command should exit with a status code of "0"
    And a file named "widget_top.assy" should contain "name: upper"
    And a file named "widget_top.assy" should not contain "name: lower"
    And a file named "widget_top.assy" should not contain "name: base"

  @success
  Scenario: A filter read from a file
    Given a file named "head.yaml" with content
      """
      tower:
      """
    When I run "pc --no-ansi filter head.yaml widget widget_tower"
    Then the command should exit with a status code of "0"
    # Named with nothing under it: the link and everything inside it stays.
    And a file named "widget_tower.assy" should contain "name: lower"
    And a file named "widget_tower.assy" should contain "name: upper"
    And a file named "widget_tower.assy" should not contain "name: base"

  @success
  Scenario: A filtered scene is a scene
    When I run "pc --no-ansi filter '[block]' table table_block"
    Then the command should exit with a status code of "0"
    And STDERR should contain "Created the scene 'table_block' from 'table'"
    And a file named "table_block.assy" should exist
    When I run "pc --no-ansi list scenes"
    Then STDERR should contain "table_block"

  @success
  Scenario: Nothing is written on a dry run
    When I run "pc --no-ansi filter --dry-run '[base]' widget widget_base"
    Then the command should exit with a status code of "0"
    And STDERR should contain "[Dry Run] Would write the assembly 'widget_base'"
    And a file named "widget_base.assy" should not exist
    And a file named "partcad.yaml" should not contain "widget_base:"

  @success
  Scenario: Re-running it replaces the file and keeps the declaration
    When I run "pc --no-ansi filter '[base]' widget widget_part"
    Then the command should exit with a status code of "0"
    When I run "pc --no-ansi filter '[tower]' widget widget_part"
    Then the command should exit with a status code of "0"
    And a file named "widget_part.assy" should contain "name: tower"
    And a file named "widget_part.assy" should not contain "name: base"

  @failure
  Scenario: A kept link connected to a dropped one is reported
    Given a file named "chain.assy" with content
      """
      links:
        - part: cube
          name: first
          location: [[0, 0, 0], [0, 0, 1], 0]
        - part: cube
          name: second
          connectPorts:
            name: first
      """
    And a file named "partcad.yaml" with content
      """
      parts:
        cube:
          type: cadquery
          path: cube.py

      assemblies:
        chain:
          type: assy
      """
    When I run "pc --no-ansi filter '[second]' chain chain_cut"
    Then the command should exit with a non-zero status code
    And STDERR should contain "nothing in this file places a link called 'first'"
    # 'pc lint' sees the same thing, from the same checker, over the file that
    # was written.
    When I run "pc --no-ansi lint --file chain_cut.assy"
    Then the command should exit with a non-zero status code
    And STDERR should contain "nothing in this file places a link called 'first'"

  @success
  Scenario: A link with no name of its own is selected by its position
    Given a file named "nested.assy" with content
      """
      links:
        - part: cube
          name: base
          location: [[0, 0, 0], [0, 0, 1], 0]
        - links:
            - part: cube
              name: inner
              location: [[0, 0, 10], [0, 0, 1], 0]
      """
    And a file named "partcad.yaml" with content
      """
      parts:
        cube:
          type: cadquery
          path: cube.py

      assemblies:
        nested:
          type: assy
      """
    When I run "pc --no-ansi filter '{link#2: null}' nested nested_group"
    Then the command should exit with a status code of "0"
    And a file named "nested_group.assy" should contain "name: inner"
    And a file named "nested_group.assy" should not contain "name: base"
    # The position is written down as the link is kept: it was the second of two
    # and is now the only one, so a position would have renamed it.
    And a file named "nested_group.assy" should contain "name: link#2"

  @success
  Scenario: A filter a render file type declares
    Given a file named "partcad.yaml" with content
      """
      parts:
        cube:
          type: cadquery
          path: cube.py

      assemblies:
        widget:
          type: assy
          render:
            svg:
              prefix: out
              filter: [base]
            png:
              prefix: out
      """
    And a directory named "out" exists
    When I run "pc --no-ansi render -a widget"
    Then the command should exit with a status code of "0"
    # Per file type: the SVG is of one link and the PNG of the whole of it.
    And a file named "out/widget.svg" should exist
    And a file named "out/widget.png" should exist

  @failure
  Scenario: A configured filter that is not a mask of link names
    Given a file named "partcad.yaml" with content
      """
      parts:
        cube:
          type: cadquery
          path: cube.py

      assemblies:
        widget:
          type: assy
          render:
            svg:
              filter: 7
      """
    When I run "pc --no-ansi render -a -t svg widget"
    Then the command should exit with a non-zero status code
    And STDERR should contain "a mapping or a list of link names is expected"

  @failure
  Scenario: A name that is not a link of the assembly
    When I run "pc --no-ansi filter '[nosuch]' widget widget_none"
    Then the command should exit with a non-zero status code
    And STDERR should contain "there is no link called 'nosuch'"

  @failure
  Scenario: A filter that is neither a file nor an expression
    When I run "pc --no-ansi filter nosuch.yaml widget widget_none"
    Then the command should exit with a status code of "2"
    And STDERR should contain "nosuch.yaml"

  @failure
  Scenario: The source and the target cannot be the same object
    When I run "pc --no-ansi filter '[base]' widget widget"
    Then the command should exit with a status code of "2"
    And STDERR should contain "is the source"

  @failure
  Scenario: An object the package does not declare
    When I run "pc --no-ansi filter '[base]' nosuch nosuch_part"
    Then the command should exit with a status code of "2"
    And STDERR should contain "is not an assembly or a scene"
