name: Developer's Handbook
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # Run daily at midnight
  push:
    branches:
      - devel
    paths:
      - ".devcontainer/**"
      - ".github/workflows/mkdocs.yml"
      - "docs/mkdocs/**"
      - "poetry.lock"
      - "pyproject.toml"

permissions:
  contents: write

env:
  CONTAINER_REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}-devcontainer
  IMAGE_TAG: ${{ github.head_ref || github.sha }}

jobs:
  mkdocs:
    name: "Build: Dev Container"
    # TODO:https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/about-actions-runner-controller#creating-your-own-runner-image
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    permissions:
      # https://docs.github.com/en/actions/security-for-github-actions/security-guides/automatic-token-authentication#permissions-for-the-github_token
      contents: read
      packages: write
    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.CONTAINER_REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Dev Container
        uses: devcontainers/ci@v0.3
        with:
          imageName: ${{ env.CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}
          imageTag: ${{ env.IMAGE_TAG }}
          cacheFrom: ${{ env.CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}
          push: never
          runCmd: |
            # Configure Git Credentials
            git config user.name github-actions[bot]
            git config user.email 41898282+github-actions[bot]@users.noreply.github.com

            # Install Dependencies
            poetry install --only=docs

            # Build & Deploy Documentation
            cd docs/mkdocs
            poetry run mkdocs gh-deploy --force
