name: nox

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - devel
  pull_request:
    branches:
      - devel

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-24.04]
        python-version: ["3.10"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: ./.github/actions/setup-all

    - name: Install prerequisites
      shell: bash
      run: |
        sudo apt-get -q update || exit 1
        sudo apt-get -q install -y \
          libxml2-dev libxslt-dev \
          libtiff5-dev libjpeg62-turbo-dev libopenjp2-7-dev zlib1g-dev \
          libfreetype6-dev liblcms2-dev libwebp-dev tcl8.6-dev tk8.6-dev \
          python3-tk libharfbuzz-dev libfribidi-dev libxcb1-dev

      - working-directory: partcad-ide-vscode
        run: python -m pip install nox
      - working-directory: partcad-ide-vscode
        run: nox --session setup
      - working-directory: partcad-ide-vscode
        run: nox --session build_package
      # TODO(clairbee): run VSCode tests (that depend on the PartCAD Python module)
