# CI on Linux, MacOS and Windows
name: CI # Keep the action badge icon short

on:
  push:
    branches: ["main", "devel"]
  pull_request:
    branches: ["main", "devel"]

permissions:
  contents: read

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-13] # macos-latest has an issue with nlopt
        python-version:
          - "3.10"
          # - "3.11"
          - "3.12"
        exclude:
          # Reduce costs by testing one version of Python on MacOS
          - os: "macos-13"
            python-version: "3.10"
          - os: "macos-13"
            python-version: "3.11"
          # False negatives on Windows for pytest result evaluation
          - os: "windows-latest"
            python-version: "3.11"
          - os: "windows-latest"
            python-version: "3.12"
    runs-on: ${{ matrix.os }}
    if: "!startsWith(github.event.head_commit.message, 'Version updated')"

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup

      # BEGIN OS-SPECIFIC
      - name: Install OS-specific dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y openscad

      - name: Install OS-specific dependencies (MacOS)
        if: runner.os == 'macOS'
        run: |
          brew install -f openscad || ( \
            rm /Users/runner/Library/Caches/Homebrew/downloads/*--OpenSCAD-*.dmg && brew install -f openscad)

      - name: Install OS-specific dependencies (Windows)
        if: runner.os == 'Windows'
        run: |
          # Prepare the registry
          reg add "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\FileSystem" /v LongPathsEnabled /t REG_DWORD /d 1 /f

          # Install OpenSCAD
          curl -o openscad.zip https://files.openscad.org/OpenSCAD-2021.01-x86-64.zip
          Expand-Archive -Force openscad.zip
          Add-Content $env:GITHUB_PATH $env:GITHUB_WORKSPACE\openscad\openscad-2021.01
      # END OS-SPECIFIC
      #
      - name: Install dependencies
        run: |
          mamba create -n test python=${{ matrix.python-version }} -y
          mamba activate test
          python -m pip install --upgrade pip
          pip install -U pytest
          # Install all core and a subset of CLI dependencies, that are required for tests
          pip install -r partcad/requirements.txt && pip install svglib rlPyCairo renderlab
          mamba deactivate

      - name: Test with pytest
        env:
          PYTHONPATH: partcad/src
          PYTHONWARNINGS: ignore
        run: |
          mamba activate test
          pytest -x -p no:error-for-skips -p no:warnings --ignore-glob="openscad*"
          mamba deactivate

      - name: Install CLI
        run: |
          mamba activate test
          pip install -U ./partcad ./partcad-cli
          mamba deactivate

      - name: Basic integration test for CLI
        run: |
          # Confirm that OpenSCAD works
          openscad --version

          mamba activate test

          # BEGIN CLEAN PACKAGE
          mkdir new_pkg
          cd new_pkg
          pc --no-ansi init
          pc --no-ansi list-all -r
          # END CLEAN PACKAGE

          # BEGIN EXAMPLES
          cd ../examples
          pc --no-ansi list-all -r
          pc --no-ansi test -r
          pc --no-ansi render -r
          # END EXAMPLES

          mamba deactivate

      - name: Basic integration test for CLI
        if: runner.os == 'Linux'
        run: |
          mamba activate test
          # BEGIN PUBLIC REPO
          pc --no-ansi test -r --package /pub/examples;
          # END PUBLIC REPO
          mamba deactivate

  # No testing resources for the below:
  #test-repo:
  #  strategy:
  #    fail-fast: false
  #    matrix:
  #      os: ["ubuntu-latest-m"]
  #      python-version: ["3.12"]
  #  runs-on: ${{ matrix.os }}
  #  if: "!startsWith(github.event.head_commit.message, 'Version updated')"
  #  steps:
  #    - uses: actions/checkout@v3
  #    - uses: ./.github/actions/setup
  #    - name: Install dependencies
  #      run: |
  #        python -m pip install --upgrade pip
  #        pip install -U pytest
  #        pip install -r partcad/requirements.txt
  #        # Install a subset of CLI dependencies, that are required for tests
  #        pip install svglib rlPyCairo renderlab
  #        # pip install -r partcad-cli/requirements.txt
  #    - name: Install OS-specific dependencies (Linux)
  #      if: runner.os == 'Linux'
  #      run: |
  #        sudo apt-get update
  #        sudo apt-get install -y openscad
  #    - name: Install OS-specific dependencies (MacOS)
  #      if: runner.os == 'macOS'
  #      run: |
  #        brew install openscad
  #    - name: Install OS-specific dependencies (Windows)
  #      if: runner.os == 'Windows'
  #      run: |
  #        curl -o openscad-installer.exe https://files.openscad.org/OpenSCAD-2021.01-x86-64-Installer.exe
  #        ./openscad-installer.exe
  #    - name: Test the entire repository
  #      run: |
  #        pip install -U ./partcad ./partcad-cli
  #        cd examples
  #        pc --no-ansi test -r --package /pub
