name: CI on Linux, MacOS and Windows

on:
  push:
    branches: ["main", "devel"]
  pull_request:
    branches: ["main", "devel"]

permissions:
  contents: read

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-13] # macos-latest has an issue with nlopt
        # os: ["ubuntu-latest", "windows-latest", "macos-latest"]
        python-version: ["3.10", "3.11", "3.12"]
        exclude:
          # Reduce costs by testing one version of Python on MacOS
          - os: "macos-13"
            python-version: "3.10"
          - os: "macos-13"
            python-version: "3.11"
        #   # False negatives on Windows for pytest result evaluation
        #   - os: "windows-latest"
        #     python-version: "3.11"
        #   - os: "windows-latest"
        #     python-version: "3.12"
    runs-on: ${{ matrix.os }}
    if: "!startsWith(github.event.head_commit.message, 'Version updated')"

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U pytest
          # Install all core and a subset of CLI dependencies, that are required for tests
          pip install -r partcad/requirements.txt && pip install svglib rlPyCairo renderlab
      - name: Install OS-specific dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y openscad
      - name: Install OS-specific dependencies (MacOS)
        if: runner.os == 'macOS'
        run: |
          brew install openscad
      - name: Install OS-specific dependencies (Windows)
        if: runner.os == 'Windows'
        run: |
          curl -o openscad-installer.exe https://files.openscad.org/OpenSCAD-2021.01-x86-64-Installer.exe
          ./openscad-installer.exe
      - name: Test with pytest
        env:
          PYTHONPATH: partcad/src
          PYTHONWARNINGS: ignore
        run: |
          pytest -x -p no:error-for-skips -p no:warnings
      - name: Basic integration test for CLI
        run: |
          pip install -U ./partcad ./partcad-cli
          mkdir new_pkg
          cd new_pkg
          pc --no-ansi init
          pc --no-ansi list-all -r
          cd ../examples
          pc --no-ansi list-all -r
          pc --no-ansi test -r
          pc --no-ansi render -r
          pc --no-ansi test -r --package /pub/examples

  test-repo:
    #strategy:
    #  fail-fast: false
    #  matrix:
    #    os: ["ubuntu-latest"]
    #    python-version: ["3.12"]
    #runs-on: ${{ matrix.os }}
    runs-on: ubuntu-latest-m
    if: "!startsWith(github.event.head_commit.message, 'Version updated')"

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U pytest
          pip install -r partcad/requirements.txt
          # Install a subset of CLI dependencies, that are required for tests
          pip install svglib rlPyCairo renderlab
          # pip install -r partcad-cli/requirements.txt
      - name: Install OS-specific dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y openscad
      - name: Install OS-specific dependencies (MacOS)
        if: runner.os == 'macOS'
        run: |
          brew install openscad
      - name: Install OS-specific dependencies (Windows)
        if: runner.os == 'Windows'
        run: |
          curl -o openscad-installer.exe https://files.openscad.org/OpenSCAD-2021.01-x86-64-Installer.exe
          ./openscad-installer.exe
      - name: Test the entire repository
        run: |
          pip install -U ./partcad ./partcad-cli
          mkdir new_pkg
          cd examples
          pc --no-ansi test -r --package /pub
