name: CI on Linux, MacOS and Windows

on:
  push:
    branches: ["main", "devel"]
  pull_request:
    branches: ["main", "devel"]

permissions:
  contents: read

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
      # "ubuntu-latest" replaced with "arc-runner-set"
        os: [arc-runner-set, windows-latest, macos-13] # macos-latest has an issue with nlopt
        # os: ["ubuntu-latest", "windows-latest", "macos-latest"]
        python-version: ["3.10", "3.11", "3.12"]
        exclude:
          # False negatives on Windows for pytest result evaluation
          - os: "windows-latest"
            python-version: "3.11"
          - os: "windows-latest"
            python-version: "3.12"
    runs-on: ${{ matrix.os }}
    if: "!startsWith(github.event.head_commit.message, 'Version updated')"

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - name: Install C/C++ Compiler
        if: ${{ matrix.os == 'arc-runner-set' }}  # Run this step only on Ubuntu
        id: install_cc
        uses: rlalik/setup-cpp-compiler@master
        with:
          compiler: latest  # You can specify 'gcc', 'clang', or specific versions like 'gcc-10'
      - name: Setup CMake
        if: ${{ matrix.os == 'arc-runner-set' }}  # Run this step only on Ubuntu
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '3.17.x'
      - name: Install Dependencies
        if: ${{ matrix.os == 'arc-runner-set' }}  # Run this step only on Ubuntu
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential gcc g++ cmake pkg-config libcairo2-dev python3-dev
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U pytest
          pip install -r partcad/requirements.txt
          # Install a subset of CLI dependencies, that are required for tests
          pip install svglib rlPyCairo renderlab
          # pip install -r partcad-cli/requirements.txt
      - name: Test with pytest
        env:
          PYTHONPATH: partcad/src
          PYTHONWARNINGS: ignore
        run: |
          pytest -x -p no:error-for-skips
      - name: Basic integration test for CLI
        run: |
          pip install -U ./partcad ./partcad-cli
          mkdir new_pkg
          cd new_pkg
          pc init
          pc list-all -r
