# CI on Linux, MacOS and Windows
name: CI # Keep the action badge icon short

on:
  workflow_dispatch:
  merge_group:
  push:
    branches: ["main", "devel"]
  pull_request:
    branches: ["main", "devel"]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test-pytest:
    name: "Pytest"
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-13, macos-latest]
        python-version: ["3.10", "3.11", "3.12"]
    runs-on: ${{ matrix.os }}
    if: ${{ !startsWith(github.event.head_commit.message, 'Version updated') }}
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-all
      - uses: ./.github/actions/setup-test

      - name: Test with pytest
        env:
          PYTHONPATH: partcad/src
          PYTHONWARNINGS: ignore
        shell: bash
        run: |
          # shellcheck disable=SC1090
          . ~/.bashrc
          # shellcheck disable=SC1090
          . ~/.bash_profile

          DIR=$(pwd)
          mamba activate test
          mkdir -pv pytest-test-results
          pytest -x -p no:error-for-skips -p no:warnings
          coverage xml --data-file=$DIR/.coverage -o $DIR/pytest-test-results/coverage.xml
          mamba deactivate

      - name: Upload test results & coverage reports to github and codecov
        uses: ./.github/actions/upload-test-results
        with:
          name: pytest-test-results
          path: pytest-test-results/
          retention-days: 7
          status: ${{ job.status }}
          token: ${{ secrets.CODECOV_TOKEN }}
          codecov-files: pytest-test-results/junit.xml
          coverage-report: pytest-test-results/coverage.xml

  test-behave:
    name: "Behave"
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-13, macos-latest]
        python-version: ["3.10", "3.11", "3.12"]
    runs-on: ${{ matrix.os }}
    if: ${{ !startsWith(github.event.head_commit.message, 'Version updated') }}
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-all
      - uses: ./.github/actions/setup-test

      - name: Test with behave
        shell: bash
        run: |
          # shellcheck disable=SC1090
          . ~/.bashrc
          # shellcheck disable=SC1090
          . ~/.bash_profile

          DIR=$(pwd)
          mkdir -pv behave-test-results

          mamba activate test
          coverage run $(which behave)
          coverage xml --data-file=./.coverage -o $DIR/behave-test-results/coverage.xml
          mamba deactivate

      - name: Upload test results & coverage reports to github and codecov
        uses: ./.github/actions/upload-test-results
        with:
          name: behave-test-results
          path: behave-test-results/
          retention-days: 7
          status: ${{ job.status }}
          token: ${{ secrets.CODECOV_TOKEN }}
          codecov-files: behave-test-results/junit.xml
          coverage-report: behave-test-results/coverage.xml

  test-examples-partcad:
    name: "Examples (PartCAD)"
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-13, macos-latest]
        python-version: ["3.10", "3.11", "3.12"]
    runs-on: ${{ matrix.os }}
    if: ${{ !startsWith(github.event.head_commit.message, 'Version updated') }}
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-all
      - uses: ./.github/actions/setup-test

      - name: Basic integration test for CLI (PartCAD examples)
        shell: bash
        run: |
          # shellcheck disable=SC1090
          . ~/.bashrc
          # shellcheck disable=SC1090
          . ~/.bash_profile

          DIR=$(pwd)
          mkdir -pv examples-partcad-test-results

          mamba activate test
          cd $DIR
          pip install -U ./partcad ./partcad-cli

          # BEGIN PARTCAD EXAMPLES
          cd ./examples
          coverage run $(which pc) --no-ansi list all -r
          coverage run $(which pc) --no-ansi test -r
          coverage run $(which pc) --no-ansi render -r
          # END PARTCAD EXAMPLES

          coverage xml --data-file=./.coverage -o $DIR/examples-partcad-test-results/coverage.xm
          mamba deactivate

      - name: Upload test results & coverage reports to github and codecov
        uses: ./.github/actions/upload-test-results
        with:
          name: examples-partcad-test-results
          path: examples-partcad-test-results/
          retention-days: 7
          status: ${{ job.status }}
          token: ${{ secrets.CODECOV_TOKEN }}
          codecov-files: examples-partcad-test-results/junit.xml
          coverage-report: examples-partcad-test-results/coverage.xml

  test-examples-all:
    name: "Examples (All)"
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-13, macos-latest]
        python-version: ["3.10", "3.11", "3.12"]
    runs-on: ${{ matrix.os }}
    if: ${{ !startsWith(github.event.head_commit.message, 'Version updated') }}
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-all
      - uses: ./.github/actions/setup-test

      - name: Basic integration test for CLI (all examples)
        shell: bash
        run: |
          # shellcheck disable=SC1090
          . ~/.bashrc
          # shellcheck disable=SC1090
          . ~/.bash_profile

          DIR=$(pwd)
          mkdir -pv examples-all-test-results

          mamba activate test
          cd $DIR
          pip install -U ./partcad ./partcad-cli

          # BEGIN ALL EXAMPLES
          cd examples
          coverage run $(which pc) --no-ansi test -r --package /pub/examples
          # END ALL EXAMPLES

          coverage xml --data-file=./.coverage -o $DIR/examples-all-test-results/coverage.xml
          mamba deactivate

      - name: Upload test results & coverage reports to github and codecov
        uses: ./.github/actions/upload-test-results
        with:
          name: examples-all-test-results
          path: examples-all-test-results/
          retention-days: 7
          status: ${{ job.status }}
          token: ${{ secrets.CODECOV_TOKEN }}
          codecov-files: examples-all-test-results/junit.xml
          coverage-report: examples-all-test-results/coverage.xml

  test-pub-repo:
    name: "Repo //pub"
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04-l, windows-latest-l]
        python-version: ["3.10", "3.12"]
    runs-on: ${{ matrix.os }}
    if: ${{ !startsWith(github.event.head_commit.message, 'Version updated') }}
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-all
      - uses: ./.github/actions/setup-test

      - name: Test the entire repository
        shell: bash
        run: |
          # shellcheck disable=SC1090
          . ~/.bashrc
          # shellcheck disable=SC1090
          . ~/.bash_profile

          DIR=$(pwd)
          mkdir -pv pub-repo-test-results

          mamba activate test
          cd $DIR
          pip install -U ./partcad ./partcad-cli

          # BEGIN PUBLIC REPO
          cd examples
          coverage run $(which pc) --no-ansi test -r --package /pub
          # END PUBLIC REPO

          coverage xml --data-file=,/.coverage -o $DIR/pub-repo-test-results/coverage.xml
          mamba deactivate


      - name: Upload test results & coverage reports to github and codecov
        uses: ./.github/actions/upload-test-results
        with:
          name: pub-repo-test-results
          path: pub-repo-test-results/
          retention-days: 7
          status: ${{ job.status }}
          token: ${{ secrets.CODECOV_TOKEN }}
          codecov-files: pub-repo-test-results/junit.xml
          coverage-report: pub-repo-test-results/coverage.xml
