name: Updates version and tags
on:
  push:
    branches: ["devel"]
permissions:
  contents: write
jobs:
  update_version_and_tag:
    runs-on: ubuntu-24.04
    if: |
      !startsWith(github.event.head_commit.message, '[SKIP]') &&
      !startsWith(github.event.head_commit.message, 'Version updated')
    environment:
      name: CD

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
      - name: Install Python 3
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Setup env variables
        run: |
          echo "SKIPBUMP=FALSE" >> "${GITHUB_ENV}"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install bump-my-version==0.16.2 setuptools wheel twine

      - name: Configure git
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      # If a commit starts with [MAJOR] a new major verion upgrade will be
      # triggered. Use with caution as Major upgrades denote backwards
      # incompatibility. Yet I like it to be integrated in the CI
      - name: Bump Major Version
        env:
          COMMIT_MSG: ${{ github.event.head_commit.message }}
        run: |
          bump-my-version bump --config-file .devcontainer/.bumpversion.toml --config-file .devcontainer/.bumpversion.toml major
          echo "SKIPBUMP=TRUE" >> "${GITHUB_ENV}"
        if: startsWith(github.event.head_commit.message, '[MAJOR]')

      - name: Bump Minor Version
        env:
          COMMIT_MSG: ${{ github.event.head_commit.message }}
        run: |
          bump-my-version bump --config-file .devcontainer/.bumpversion.toml minor
          echo "SKIPBUMP=TRUE" >> "${GITHUB_ENV}"
        if: startsWith(github.event.head_commit.message, '[FEATURE]')

      # Default action
      - name: Bump Patch Version
        env:
          COMMIT_MSG: ${{ github.event.head_commit.message }}
        run: |
          bump-my-version bump --config-file .devcontainer/.bumpversion.toml patch
        if: env.SKIPBUMP == 'FALSE'

      - name: Commit version change to repo
        run: |
          git push --force --follow-tags
