site_name: Technonomicon
site_url: https://github.com/partcad/partcad

theme: material
markdown_extensions:
  - mdx_truly_sane_lists:
      nested_indent: 2
      truly_sane: true
  - pymdownx.tasklist:
      custom_checkbox: true
